build: update java to 8+
Building with OpenJDK 23 leads to the following error:

warning: [options] bootstrap class path is not set in conjunction with -source 7
  not setting the bootstrap class path may lead to class files that cannot run on JDK 8
    --release 7 is recommended instead of -source 7 -target 7 because it sets the bootstrap class path automatically
error: Source option 7 is no longer supported. Use 8 or later.
error: Target option 7 is no longer supported. Use 8 or later.

Upgrading to Java 8 fixes the issue since Java 7 is deprecated

Signed-off-by: Anshul Dalal <anshulusr@gmail.com>